### ISSUE TITLE
Cannot login github account

### ISSUE THREAD

**Issue by Zrincet** [aalok05/CodeHub#132]
![tim 20181107174109](https://user-images.githubusercontent.com/11169330/48123225-569e3680-e2b4-11e8-8402-16ad394acd73.png)
Authorize button is disabled.

**Comment by aalok05** [comment]
Hmmmm wierd.

**Comment by rafsanulhasan** [comment]
Hi @aalok05,
I think the changed app Id and key in app config is causing the problem since you have changed it in the dev branch. While deployment to have to change it back to original one. Though in my PC, its working without any issues

**Comment by aalok05** [comment]
@Zrincet  Is this screenshot from the store app? Or are you running the solution locally?

**Comment by KaziFarhanuddin** [comment]
same issue

**Comment by redblue9771** [comment]
same issue + 1 

windows 1809 and above

**Comment by Zrincet** [comment]
@aalok05 App downloaded in the Microsoft Store，and the version of windows10 is 1809.

**Comment by aalok05** [comment]
Ok, working on this.

**Comment by rafsanulhasan** [comment]
@aalok05, I am facing the same issue too after revoking permission from GitHub OAuth App. It might be solved by updating the Windows UWP SDK itself from the NuGet. 

I found another issue related to it maybe, it is showing a warning that Internet Explorer (IE) is no longer supported. This happened because when you are calling WebAuthenticationBroker from the AuthService, it might be getting/using IE behind the scenes to show the OAuth Login window from GitHub. Updating the UWP SDK  might solve the problem because the latest SDK might be using Edge instead of IE, but I'm not sure really. Try using other ways to show up the OAuth Dialog might solve the issue.

**Comment by aalok05** [comment]
I think the two issues are related. JS is not enabled in the webview.
https://stackoverflow.com/questions/44425233/why-is-the-github-authorization-button-in-the-oauth-flow-grayed-out

**Comment by aalok05** [comment]
I'll update the UWP SDK and if this works, I'll submit to store ASAP. Thanks for your patience.

**Comment by aalok05** [comment]
https://social.msdn.microsoft.com/Forums/en-US/ff3631c1-9264-47d7-9906-107a0614cdd7/uwp-how-to-set-webauthenticationbroker-to-use-edge-instead-of-ie?forum=wpdevelop

**Comment by rafsanulhasan** [comment]
custom flow for OAuth is always the best solution for any mobile/web/desktop app. I wish GitHub would have supported OpedID Connect along with OAuth.

**Comment by rafsanulhasan** [comment]
@aalok05 I think instead of implicit flow you should use hybrid flow for better security

**Comment by rafsanulhasan** [comment]
Microsoft is making Edge a Chromium based Browser and going to bring it into UWP. I hope it's gonna work then...

**Comment by duxingzhe** [comment]
Please update your UWP app. I can't use it completely now. That's trouble experience. I want to use UWP to view Github.com instead of the web. Please update it as soon as possible.

**Comment by aberus** [comment]
This could resolve this issue
https://peterfoot.net/2019/03/13/webauthenticationbroker-and-github/
https://github.com/inthehand/Authful

**Comment by aalok05** [comment]
@aberus Thanks, will have a look.

**Comment by aalok05** [comment]
@aberus This is awesome. It’s exactly what we need.
