### ISSUE TITLE
Add indicator for notifications on the bell

### ISSUE THREAD

**Issue by kumarharsh** [aalok05/CodeHub#41]
Right now, there is no indication that there are unread notifications.

**Comment by Sergio0694** [comment]
@aalok05 In order to implement this we'd have to make an additional API request every time the page is loaded again to check if there are new notifications. Since this might impact on the data usage/battery, it might be a good idea to turn it on by default on PCs, and add a setting for it on mobile phones.

**Comment by aalok05** [comment]
This is a good one. I was thinking about this. @Sergio0694 we might have to make a setting, for now we'll just go ahead and make a call every time a page is loaded.

**Comment by aalok05** [comment]
PR is in progress https://github.com/aalok05/CodeHub/tree/feature_unread_notif_indicator

**Comment by aalok05** [comment]
#57 adds this feature.
