### ISSUE TITLE
French

### ISSUE THREAD

**Issue by PoLaKoSz** [aalok05/CodeHub#75]
Write a comment with the translation or commit to #72, please. Thanks 😄 🍺

## **Search**

|                | Status |
|----------------|:--:|
| All Languages | ✅ |
| Reset | ✅ |

## **Settings / Donate**

|                | Status |
|----------------|:--:|
| Donate to CodeHub on Patreon | ✅ |

## **Settings / General**

|                | Status |
|----------------|:--:|
| Make any donation to enable the option to disable ads. | ✅ |

## **Settings / About**

|                | Status |
|----------------|:--:|
| What's new in this version? | ✅ |
| Developed by Aalok Singh | ✅ |

## **Time Ago converter**

|                | Status |
|----------------|:--:|
| one second ago | ✅ |
| seconds ago    | ✅ |
| a minute ago   | ✅ |
| minutes ago    | ✅ |
| an hour ago    | ✅ |
| hours ago      | ✅ |
| a day ago      | ✅ |
| days ago       | ✅ |
| one month ago  | ✅ |
| months ago     | ✅ |
| one year ago   | ✅ |
| years ago      | ✅ |

**Comment by Darkpingouin** [comment]
All Languages -> Tous les langues
Reset -> Réinitialiser

Donate to CodeHub on Patreon -> Faire un don à CodeHub sur Patreon 

Make any donation to enable the option to disable ads. -> Faites n'importe quel don pour activer l'option enlever les pubs

What's new in this version? -> Quoi de neuf dans cette version?
Developed by Aalok Singh -> Developpe par Aalok Singh

For the time it is a bit complicated since 
2 seconds ago = Il y a 2 secondes (so I don't really know how to translate it ?)

one second ago -> Il y a une seconde
seconds ago -> Il y a #NB seconds
a minute ago -> Il y a une minute
minutes ago -> Il y a #NB minutes
an hour ago -> Il y a une heure
hours ago -> Il y a #NB heures
a day ago -> Il y a un jour
days ago -> Il y a #NB jours
one month ago -> Il y a un mois
months ago -> il y a #NB mois
one year ago -> Il y a un an
years ago -> Il y a #NB ans

Let me know if this is ok, and I will put it in the FR strings file and create a pull request then. 
![bitmoji](https://render.bitstrips.com/v2/cpanel/10223075-186542375_10-s4-v1.png?transparent=1&palette=1&width=246)

**Comment by aalok05** [comment]
@PoLaKoSz please have a look

**Comment by PoLaKoSz** [comment]
@Darkpingouin Is there a way to put the number in front of the words?
like
`10` minutes ago?
Or in french there is no ways for this? 😢

**Comment by aalok05** [comment]
Now that's a problem

**Comment by aalok05** [comment]
Let's remove the 'ago' part then. 

one second -> une seconde
seconds -> seconds
a minute -> une minute
minutes  -> minutes
an hour ->  une heure
hours  -> heures
a day -> un jour
days -> jours
one month -> un mois
months ->  mois
one year -> un an
years -> ans

How about this @Darkpingouin  and @PoLaKoSz ?

**Comment by Darkpingouin** [comment]
@PoLaKoSz I am afraid there is no other way to translate it in french.
@aalok05 I would just let the English sentences then because like that it doesn't make sense to me I don't know what you think.

**Comment by PoLaKoSz** [comment]
No problem I saw a few days ago an another solution when a variable (in this case a number) can be inside a localized sentence.
But nowadays I don't have too much time maybe I can code it in this weekend.

**Comment by aalok05** [comment]
ok so let it be in english then.

**Comment by aalok05** [comment]
@PoLaKoSz let's leave in it english for now, later when you have time maybe you can implement your solution, but for now its fine.
